longhorn:
  persistence:
    defaultClassReplicaCount: 2
  preUpgradeChecker:
    jobEnabled: false
  defaultSettings:
    defaultDataPath: /mnt/longhorn
    createDefaultDiskLabeledNodes: true
  service:
    ui:
      type: LoadBalancer
      loadBalancerIP: 192.168.0.241
      nodePort: 32000